version: '3'
services:
  backend:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
